### ISSUE TITLE
DependsOn Property

### ISSUE THREAD

**Issue by ArturNawrocki** [PowerBI-tips/TabularEditor-Scripts#4]
Hello guys,

Out of curiosity. Daniel in one of the scripts is using DependsOn property. It is popping up as available property with TE, but I cannot find it https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.measure?view=analysisservices-dotnet as available property. Do you know maybe what is going on here?

PS. As I am still new to both Github/C# thing let me know if this right place to ask those questions

**Comment by JamesDBartlett3** [comment]
@ArturNawrocki Can you link to Daniel's script that you're referring to, so I can take a look at it?

**Comment by MikeCarlo** [comment]
Here is a discussion on how the DependsOn works: https://github.com/TabularEditor/TabularEditor/issues/637
