### ISSUE TITLE
Create MPartition

### ISSUE THREAD

**Issue by elsdestickere** [PowerBI-tips/TabularEditor-Scripts#5]
Hi, i'm trying to create an M partition in Tabular editor.
I'm stuck at changing the mode property. The help suggests to use a set, but I can't figure out how...

var newMpartition= "f_ha_birth_incrementalM";
var tableMpartition="births (facts)";
var partition= Model.Tables[tabelMpartition].AddMPartition(newMpartition);
// I can select the import value
var modePart= partition.Mode.Import;
// but how do you update the mode?
partition.Mode{set modePart;}

**Comment by ArturNawrocki** [comment]
Have you tried  // partition.Mode = "Import"

**Comment by JamesDBartlett3** [comment]
@elsdestickere, did @ArturNawrocki's suggestion above solve your problem?
